---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: amazonlinux1
    image: amazonlinux:2
    command: /sbin/init
    privileged: True  
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: pacemaker
    network_mode: pacemaker
  - name: amazonlinux2
    image: amazonlinux:2
    command: /sbin/init
    privileged: True  
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: pacemaker
    network_mode: pacemaker
  - name: amazonlinux3
    image: amazonlinux:2
    command: /sbin/init
    privileged: True  
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: pacemaker
    network_mode: pacemaker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'