---
# tasks file for pcs
- name: Include OS-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "defaults"
        - "vars"
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - "default.yml"
        - "main.yml"
  when: pacemaker_packages is not defined
  tags:
    - "vars"

- name: Install pacemaker packages
  package:
    name: "{{ pacemaker_packages }}"

# ChangeToVaultP@55w0rd_
- name: Create the hacluster user
  user:
    name: hacluster
    comment: User for the Pacemaker software
    password: $6$V8GTXhwF8739PPUv$uvg.hPSNk8vCEJJ2tLCqihhSsODVbFymQuyux5zhbDCKcPgZqEX5sT97ECioWSgxvDDoEKJOs7kchqFVLy0mK1
    shell: /bin/bash

#- name: Allow HA in firewalld
#  ansible.posix.firewalld:
#    service: high-availability
#    permanent: true
#    immediate: true
#    state: enabled

- name: Start the pcsd service
  service:
    name: pcsd
    state: started
    enabled: yes