---
# tasks file for pcs
- name: Install pacemaker packages
  package:
    name:
      - pcs
      - pacemaker
      - fence-agents-all
      - lvm2-cluster 
      - gfs2-utils

# ChangeToVaultP@55w0rd_
- name: Create the hacluster user
  user:
    name: hacluster
    comment: User for the Pacemaker software
    password: $6$V8GTXhwF8739PPUv$uvg.hPSNk8vCEJJ2tLCqihhSsODVbFymQuyux5zhbDCKcPgZqEX5sT97ECioWSgxvDDoEKJOs7kchqFVLy0mK1
    shell: /bin/bash

#- name: Allow HA in firewalld
#  ansible.posix.firewalld:
#    service: high-availability
#    permanent: true
#    immediate: true
#    state: enabled

- name: Start the pcsd service
  service:
    name: pcsd
    state: started
    enabled: yes